language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: beta
        - rust: nightly
dist: trusty
sudo: false
addons:
    apt:
        packages:
            - python3-pip
before_install:
    - wget https://storage.googleapis.com/wasm-llvm/builds/linux/26619/wasm-toolchain_0.1.26619_amd64.deb
    - sudo dpkg -i wasm-toolchain_0.1.26619_amd64.deb
install:
    - pip3 install --user --upgrade mypy flake8
    - travis_wait ./check-rustfmt.sh --install
script: ./test-all.sh
cache:
    cargo: true
    directories:
        - $HOME/.cache/pip
